### ISSUE TITLE
Fail on AWS (API?)

### ISSUE THREAD

**Issue by esunar** [esunar/test-repo#206]
Even if I try to deploy using --constraints "mem=4G", I get this error after deploying this bundle on AWS.

```
series: bionic
applications:
  elasticsearch:
    charm: cs:~elasticsearch-charmers/elasticsearch-20
    num_units: 1
    to:
    - "2"
    constraints: mem=4096
  graylog:
    charm: cs:~graylog-charmers/graylog-50
    num_units: 1
    to:
    - "0"
    expose: true
    constraints: mem=4096
  mongodb:
    charm: cs:~mongodb-charmers/mongodb-11
    num_units: 1
    to:
    - "1"
machines:
  "0":
    constraints: mem=4096
  "1": {}
  "2":
    constraints: mem=4096
relations:
- - graylog:mongodb
  - mongodb:database
- - graylog:elasticsearch
  - elasticsearch:client

```
